/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppointmentRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'treatmentType' : IDL.Text,
});
export const ContactRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
  'deleteContactRequest' : IDL.Func([IDL.Nat], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(AppointmentRequest)], ['query']),
  'getAllContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [AppointmentRequest], ['query']),
  'getContactRequest' : IDL.Func([IDL.Nat], [ContactRequest], ['query']),
  'submitAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContactRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppointmentRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'treatmentType' : IDL.Text,
  });
  const ContactRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
    'deleteContactRequest' : IDL.Func([IDL.Nat], [], []),
    'getAllAppointments' : IDL.Func(
        [],
        [IDL.Vec(AppointmentRequest)],
        ['query'],
      ),
    'getAllContactRequests' : IDL.Func(
        [],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getAppointment' : IDL.Func([IDL.Nat], [AppointmentRequest], ['query']),
    'getContactRequest' : IDL.Func([IDL.Nat], [ContactRequest], ['query']),
    'submitAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContactRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };