/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentRequest {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'timestamp' : bigint,
  'phone' : string,
  'treatmentType' : string,
}
export interface ContactRequest {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface _SERVICE {
  'deleteAppointment' : ActorMethod<[bigint], undefined>,
  'deleteContactRequest' : ActorMethod<[bigint], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<AppointmentRequest>>,
  'getAllContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getAppointment' : ActorMethod<[bigint], AppointmentRequest>,
  'getContactRequest' : ActorMethod<[bigint], ContactRequest>,
  'submitAppointment' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'submitContactRequest' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];